name: user_articles
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.3
  get_it: ^7.6.4
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.6.2
  retrofit_generator: ^7.0.0

flutter:
  uses-material-design: true
